/**
 * helpers.jsx — Chronos Admin / Schedule
 * ──────────────────────────────────────────────────────────────────────────
 * Shared module-level helpers & consts used across the Schedule tabs.
 *   - Demo data layer (active when solver is offline or backend is empty)
 *   - subjectColor (Assignments + Timetables)
 *   - Spinner (all tabs)
 *   - EVENT_TYPES / evtCfg (Calendar)
 * ──────────────────────────────────────────────────────────────────────────
 */
import React from 'react';
import { theme as T } from '@/theme';

/* ═══════════════════════════════════════════════════════════════
   DEMO DATA  — active when solver is offline or backend is empty
   All demo IDs start with 'demo-' so the real API is never called.
   Data lives in localStorage under 'chronos.demo.timetables'.
   ═══════════════════════════════════════════════════════════════ */
const DEMO_KEY  = 'chronos.demo.timetables';
export const isDemoId  = (id) => typeof id === 'string' && id.startsWith('demo-');

const _buildGrid = (entries) => {
  const grid = Array.from({ length: 5 }, () => Array.from({ length: 8 }, () => []));
  let ei = 0;
  for (let day = 0; day < 5; day++) {
    for (let slot = 0; slot < 8; slot++) {
      if (slot === 4) continue; // lunch
      if (ei < entries.length) { grid[day][slot] = [entries[ei % entries.length]]; ei++; }
    }
  }
  return grid;
};

const DEMO_SEED = [
  {
    _id: 'demo-1', status: 'published', academicYear: '2025-26', semester: 3, currentVersion: 2,
    class: { _id: 'demo-cls-1', name: 'CSE 3rd Sem A', code: 'CSE3A', section: 'A', semester: 3, program: { name: 'B.Tech CSE', department: { name: 'Computer Science' } } },
    schedule: _buildGrid([
      { subject: 'Data Structures',     teacher: 'Dr. A. Sharma',  classroom: 'Room 101' },
      { subject: 'Database Management', teacher: 'Prof. R. Gupta', classroom: 'Room 102' },
      { subject: 'Computer Networks',   teacher: 'Dr. S. Patel',   classroom: 'Lab 201'  },
      { subject: 'Operating Systems',   teacher: 'Prof. M. Singh', classroom: 'Room 103' },
      { subject: 'Mathematics III',     teacher: 'Dr. P. Rao',     classroom: 'Room 104' },
      { subject: 'Software Engg.',      teacher: 'Prof. K. Verma', classroom: 'Room 105' },
      { subject: 'DS Lab',              teacher: 'Dr. A. Sharma',  classroom: 'Lab 202'  },
    ]),
    history: [
      { versionNumber: 1, changeDescription: 'Auto-generated by solver', timestamp: new Date(Date.now() - 86400000 * 3).toISOString(), editedBy: { firstName: 'Admin', lastName: '' } },
      { versionNumber: 2, changeDescription: 'Swapped Wed slot 2 ↔ Thu slot 1', timestamp: new Date(Date.now() - 86400000).toISOString(), editedBy: { firstName: 'Admin', lastName: '' } },
    ],
  },
  {
    _id: 'demo-2', status: 'draft', academicYear: '2025-26', semester: 5, currentVersion: 1,
    class: { _id: 'demo-cls-2', name: 'CSE 5th Sem B', code: 'CSE5B', section: 'B', semester: 5, program: { name: 'B.Tech CSE', department: { name: 'Computer Science' } } },
    schedule: _buildGrid([
      { subject: 'Machine Learning',      teacher: 'Dr. N. Joshi',   classroom: 'Lab 301'  },
      { subject: 'Compiler Design',       teacher: 'Prof. V. Kumar', classroom: 'Room 201' },
      { subject: 'Computer Graphics',     teacher: 'Dr. T. Mehta',   classroom: 'Lab 302'  },
      { subject: 'Theory of Computation', teacher: 'Prof. S. Bose',  classroom: 'Room 202' },
      { subject: 'Elective I – AI',       teacher: 'Dr. N. Joshi',   classroom: 'Room 203' },
      { subject: 'ML Lab',                teacher: 'Dr. N. Joshi',   classroom: 'Lab 301'  },
      { subject: 'Project Work',          teacher: 'Prof. V. Kumar', classroom: 'PG Lab'   },
    ]),
    history: [
      { versionNumber: 1, changeDescription: 'Demo — solver offline', timestamp: new Date().toISOString(), editedBy: { firstName: 'Admin', lastName: '' } },
    ],
  },
  {
    _id: 'demo-3', status: 'draft', academicYear: '2025-26', semester: 1, currentVersion: 1,
    class: { _id: 'demo-cls-3', name: 'IT 1st Sem A', code: 'IT1A', section: 'A', semester: 1, program: { name: 'B.Tech IT', department: { name: 'Information Technology' } } },
    schedule: _buildGrid([
      { subject: 'Programming in C',        teacher: 'Prof. A. Desai', classroom: 'Lab 101'  },
      { subject: 'Engineering Mathematics', teacher: 'Dr. B. Sharma',  classroom: 'Room 301' },
      { subject: 'Physics',                 teacher: 'Prof. C. Nair',  classroom: 'Room 302' },
      { subject: 'English Communication',   teacher: 'Dr. D. Roy',     classroom: 'Room 303' },
      { subject: 'Introduction to IT',      teacher: 'Prof. A. Desai', classroom: 'Room 304' },
      { subject: 'C Programming Lab',       teacher: 'Prof. A. Desai', classroom: 'Lab 101'  },
    ]),
    history: [
      { versionNumber: 1, changeDescription: 'Demo — solver offline', timestamp: new Date().toISOString(), editedBy: { firstName: 'Admin', lastName: '' } },
    ],
  },
];

export const DEMO_CLASSES = DEMO_SEED.map(t => t.class);

const _demoGet  = () => { try { const r = localStorage.getItem(DEMO_KEY); if (r) return JSON.parse(r); } catch {} localStorage.setItem(DEMO_KEY, JSON.stringify(DEMO_SEED)); return JSON.parse(JSON.stringify(DEMO_SEED)); };
const _demoSet  = (all) => localStorage.setItem(DEMO_KEY, JSON.stringify(all));
export const getDemoTimetables  = ()       => _demoGet();
export const getDemoTimetable   = (id)     => _demoGet().find(t => t._id === id) || null;
export const deleteDemoTT       = (id)     => { _demoSet(_demoGet().filter(t => t._id !== id)); };
export const publishDemoTT      = (id)     => { const all = _demoGet(); const t = all.find(x => x._id === id); if (t) { t.status = 'published'; _demoSet(all); } };
export const saveDemoEdit       = (id, schedule, desc = 'Manual edits') => {
  const all = _demoGet(); const tt = all.find(t => t._id === id); if (!tt) return null;
  const v = tt.currentVersion + 1;
  tt.history.push({ versionNumber: v, changeDescription: desc, timestamp: new Date().toISOString(), editedBy: { firstName: 'Admin', lastName: '' } });
  tt.currentVersion = v; tt.schedule = schedule; _demoSet(all); return JSON.parse(JSON.stringify(tt));
};
export const revertDemoVersion  = (id, vn) => {
  const all = _demoGet(); const tt = all.find(t => t._id === id); if (!tt) return null;
  const v = tt.currentVersion + 1;
  tt.history.push({ versionNumber: v, changeDescription: `Reverted to v${vn}`, timestamp: new Date().toISOString(), editedBy: { firstName: 'Admin', lastName: '' } });
  tt.currentVersion = v; _demoSet(all); return JSON.parse(JSON.stringify(tt));
};
export const buildDemoTT = (cls, acYear = '2025-26') => {
  const entries = [
    { subject: 'Subject A', teacher: 'Teacher 1', classroom: 'Room 101' },
    { subject: 'Subject B', teacher: 'Teacher 2', classroom: 'Room 102' },
    { subject: 'Subject C', teacher: 'Teacher 3', classroom: 'Lab 201'  },
    { subject: 'Subject D', teacher: 'Teacher 1', classroom: 'Room 103' },
    { subject: 'Subject E', teacher: 'Teacher 4', classroom: 'Room 104' },
  ];
  const tt = { _id: `demo-${Date.now()}`, status: 'draft', academicYear: acYear, semester: cls.semester || 1, currentVersion: 1, class: cls,
    schedule: _buildGrid(entries),
    history: [{ versionNumber: 1, changeDescription: 'Demo — solver offline', timestamp: new Date().toISOString(), editedBy: { firstName: 'Admin', lastName: '' } }],
  };
  const all = _demoGet(); all.push(tt); _demoSet(all); return tt;
};

/* ═══════════════════════════════════════════════════════════════
   SHARED CONSTANTS & HELPERS
   ═══════════════════════════════════════════════════════════════ */

/* Hash a subject code into a stable color from the brand palette */
const SUBJECT_PALETTE = [
  { fg: T.accent, bg: T.accentSoft, border: T.accentBorder },
  { fg: T.blue,   bg: T.blueSoft,   border: 'rgba(59,130,246,0.25)' },
  { fg: T.green,  bg: T.greenSoft,  border: 'rgba(16,185,129,0.25)' },
  { fg: T.amber,  bg: T.amberSoft,  border: 'rgba(245,158,11,0.25)' },
  { fg: '#ec4899', bg: '#fce7f3',   border: 'rgba(236,72,153,0.25)' },
  { fg: '#06b6d4', bg: '#cffafe',   border: 'rgba(6,182,212,0.25)' },
  { fg: '#f97316', bg: '#ffedd5',   border: 'rgba(249,115,22,0.25)' },
  { fg: '#84cc16', bg: '#ecfccb',   border: 'rgba(132,204,22,0.25)' },
];
export const subjectColor = (code = '') => {
  let hash = 0;
  for (let i = 0; i < code.length; i++) hash = (hash * 31 + code.charCodeAt(i)) | 0;
  return SUBJECT_PALETTE[Math.abs(hash) % SUBJECT_PALETTE.length];
};

/* Spinner used in cards / sections */
export const Spinner = ({ text = 'Loading…' }) => (
  <div style={{ padding: 56, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12 }}>
    <div style={{
      width: 28, height: 28, borderRadius: '50%',
      border: `3px solid ${T.accentSoft}`, borderTopColor: T.accent,
      animation: 'spin 0.7s linear infinite',
    }} />
    <span style={{ fontSize: 13, color: T.text3, fontWeight: 500 }}>{text}</span>
  </div>
);

/* Event-type config for the Calendar tab */
export const EVENT_TYPES = [
  { value: 'holiday',  label: 'Holiday',  color: T.red,   bg: T.redSoft },
  { value: 'exam',     label: 'Exam',     color: T.amber, bg: T.amberSoft },
  { value: 'event',    label: 'Event',    color: T.blue,  bg: T.blueSoft },
  { value: 'vacation', label: 'Vacation', color: T.green, bg: T.greenSoft },
];
export const evtCfg = (type) => EVENT_TYPES.find(e => e.value === type) || EVENT_TYPES[2];
